hypixel:
  basic:
    heart:
      emoticon: ':xin:'
      emoji: '&c❤'
    star:
      emoticon: ':star:'
      emoji: '&6✮'
    'true':
      emoticon: ':yes:'
      emoji: '&a✔'
    'false':
      emoticon: ':no:'
      emoji: '&c✖'
    java:
      emoticon: ':java:'
      emoji: '&b☕'
    arrow:
      emoticon: ':arrow:'
      emoji: '&e➜'
    shrug:
      emoticon: ':wunai:'
      emoji: '&e¯\\_(ツ)_/¯'
    tableflip:
      emoticon: ':xianzhuo:'
      emoji: '&c(╯°□°）╯&r&f︵&r&7 ┻━┻'
    wave:
      emoticon: o/
      emoji: '&d( ﾟ◡ﾟ)/'
    '123':
      emoticon: ':123:'
      emoji: '&a1&r&e2&r&c3'
    totem:
      emoticon: ':tuteng:'
      emoji: '&b☉&r&e_&r&b☉'
    typing:
      emoticon: ':xiezi:'
      emoji: '&e✎&r&6...'
    maths:
      emoticon: ':shuxue:'
      emoji: '&a√&r&e&l(&r&aπ&r&a&l+x&r&e&l)&r&a&l=&r&c&lL'
    snail:
      emoticon: ':woniu:'
      emoji: '&e@&r&a''&r&e-&r&a'''
    thinking:
      emoticon: ':sikao:'
      emoji: '&6(&r&a0&r&6.&r&ao&r&c?&r&6)'
    gimme:
      emoticon: ':geiwo:'
      emoji: '&b༼つ◕_◕༽つ'
    wizard:
      emoticon: ':mofa:'
      emoji: '&e(&r&b''&r&e-&r&b''&r&e)⊃&r&c━&r&d☆ﾟ.*･｡ﾟ'
    pvp:
      emoticon: ':pvp:'
      emoji: '&e⚔'
    peace:
      emoticon: ':peace:'
      emoji: '&a✌'
    oof:
      emoticon: ':oof:'
      emoji: '&c&lOOF'
    puffer:
      emoticon: ':chuixu:'
      emoji: '&e&l<(''O'')>'
  premium:
    snow:
      emoticon: ':xueren:'
      emoji: '&b☃'
    yey:
      emoticon: ':ye:'
      emoji: '&aヽ (◕◡◕) ﾉ'
    sloth:
      emoticon: ':landuo:'
      emoji: '&6(&r&8・&r&6⊝&r&8・&r&6)'
    hey:
      emoticon: h/
      emoji: '&eヽ(^◇^*)/'
    cat:
      emoticon: ':cat:'
      emoji: '&e= &r&b＾● ⋏ ●＾&r&e ='
    dab:
      emoticon: ':huanhu:'
      emoji: '&d<&r&eo&r&d/'
    dog:
      emoticon: ':dog:'
      emoji: '&6(ᵔᴥᵔ)'
    joy:
      emoticon:
      - ^_^
      - ^-^
      emoji: '&a$1'
    dj:
      emoticon: ':dj:'
      emoji: '&9ヽ&r&5(&r&d⌐&r&c■&r&6_&r&e■&r&b)&r&3ノ&r&9♬'
    cute:
      emoticon: ':keai:'
      emoji: '&e(&r&a✿&r&e◠‿◠)'
facepalm:
  emoticon: ':wulian:'
  emoji: '&6(&e－‸ლ&6)'
skull:
  emoticon: ':tou:'
  emoji: '&7☠'
uwu:
  emoticon: UwU
  emoji: '&d$1'
owo:
  emoticon: OwO
  emoji: '&b$1'
happy:
  emoticon: :)
  emoji: ☺
sad:
  emoticon: :(
  emoji: ☹
music:
  emoticon: ':music:'
  emoji:
  - '&c♫'
  - '&9♬'
  - '&3♪'
  - '&5♩'
  - '&a♭'
  - '&e♪'
playername:
  emoticon: ':playername:'
  emoji: '&9%player_name%'
settings:
  use:
    books: true
    signs: true
